> Dionysios Rigatos <br />
> dionysir@stud.ntnu.no <br />

[Back to Assignment 5](_Oving5.ipynb)

# The Secant Method

**Læringsmål:**
- functions
- loops

**Starting Out with Python:**
- ch. 4.2-4.3
- ch. 5.5
- ch. 5.8-5.9

In this task we will implement the Secant method in Python

The Secant method can be used to find the roots of a mathematical function. The roots of a mathematical function is where $f(x) = 0$, i.e. where the graph crosses the x-axis. 

The secant method is defined by the recurrence relation:

$x_{k+1}=x_k-f(x_k)\frac{x_k-x_{k-1}}{f(x_k)-f(x_{k-1})}$

## a)

Write a function `f` with argument `x` that returns the value of the following equation:

$f(x)=(x-12)e^{x/2}-8(x+2)^{2}$.

Write another function `g` with argument `x` that reuturns the value of:

$g(x)=-x-2x^{2}-5x^{3}+6x^{4}$.

***Write the code in the block below***

In [26]:
import math

def f(x):
    return (x-12)*math.e**(x/2) - 8*(x+2)**2

def g(x):
    return -x - 2*x**2 - 5 * x**3 + 6*x**4

In [27]:
print(f(0))
print(g(1))

-44.0
-2


You should test your code by trying the functions with different values. E.g. check that `f(0)` returns`-44` and `g(1)` returns `-2`.

## b)

The Secant method is an approximation of Newton's method:

$x_{k+1}=x_{k}-\frac{f(x_{k})}{f'(x_{k})}$ where

$f'(x_k) \approx \frac{f(x_{k})- f(x_{k-1})}{x_{k}-x_{k-1}}$

Write a function `differentiate(x_k, x_k1, func)` which uses the formula for the approximated (**f'(x)**) given in the task description to differentiate. The function should take three arguments: `x_k`, `x_k1` and `func`, and return the derivative value (a float):

- `x_k`: the point at which we want to find the derivative
- `x_k1`: an earlier point which we use to find a slope
- `func`: the function we want to differentiate(in this task `func` will allways be either `f` or `g` from **a)**)

***Write the code in the block below***

In [28]:
def differentiate(x_k, x_k1, func):
    return (func(x_k1) - func(x_k))/(x_k1 - x_k)

Test it by running `differentiate(9,10,f)`. This should return: `-210.7749243035878`

In [29]:
print(differentiate(9, 10, f))

-210.7749243035878


## c)

Write a function `secant_method(x0, x1, func, tol)` which uses `differentiate(x_k, x_k1, func)` to implement the Secant method. The function should return (stop iterating) when the change in `x` is less than the tolerance limit `tol`.

Test your function with the following values:
```python
secant_method(11,13,f,0.00001)
secant_method(1,2,g,0.00001)
secant_method(0,1,g,0.00001)
```

***Write the code in the block below***

In [30]:
def secant_method(x0, x1, func, tol):
    while abs(x1 - x0) > tol:
        x2 = x1 - func(x1) * differentiate(x0, x1, func) ** -1
        x0 = x1 
        x1 = x2
    print(f"The function is close to a root when x = {round(x1, 2)}, with value f(x) = {func(x1)}")

In [31]:
secant_method(11, 13, f, 0.00001)
secant_method(1, 2, g, 0.00001)
secant_method(0, 1, g, 0.00001)

The function is close to a root when x = 13.92, with value f(x) = -1.587634187671938e-06
The function is close to a root when x = 1.22, with value f(x) = -9.66315703010423e-08
The function is close to a root when x = 0.0, with value f(x) = 0.0


**Example run:**
```
The function is close to a root when x = 13.92 , with value f(x) =  -1.59e-06
The function is close to a root when x =  1.22 , with value f(x) =  -9.66e-08
The function is close to a root when x =  0.0  , with value f(x) =  0.0
```

#### Hint

As you can see, the secant method needs two previous points to find a new one. Be sure to replace the points as needed.